name: 'Dependabot vulnerabilities notification to Slack'

on:
  schedule:
    - cron: '0 10 * * 1' # At 10:00 on Monday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Notify-Vulnerabilites:
    runs-on: ubuntu-latest
    steps:
      # Latest version available at: https://github.com/kunalnagarco/action-cve/releases
      - name: Notify Vulnerabilities
        uses: kunalnagarco/action-cve@v1.7.33
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
